
# Project information
site_name: Phalcon Documentation
site_url: https://docs.phalcon.io
site_author: Phalcon Team
site_description: >-
  Phalcon Framework. A full-stack PHP framework delivered as a PHP extension,
  offering lower resource consumption and high performance.

# Repository
repo_name: phalcon/docs
repo_url: https://github.com/phalcon/docs

# Copyright
copyright: Copyright &copy; 2012 - present Phalcon Team

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate


  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: teal
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Titillium Web
    code: Source Code Pro
  favicon: assets/images/favicon.ico
  logo: https://assets.phalcon.io/phalcon/images/svg/phalcon-logo-white-105x40.svg

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
        'index.md': 'introduction.md'

# Hooks
#hooks:
#  - material/overrides/hooks/shortcodes.py
#  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  version:
    default: 5.4.0
    provider: mike
  annotate:
    json: [ .s2 ]
  social:
    - icon: fontawesome/brands/discord
      link: https://phalcon.io/discord
      name: Discord
    - icon: material/comment
      link: https://phalcon.io/discussions
      name: GitHub Discussions
    - icon: fontawesome/brands/github
      link: https://phalcon.io/github
      name: GitHub Project
    - icon: fontawesome/brands/telegram
      link: https://phalcon.io/telegram
      name: Telegram
    - icon: fontawesome/solid/frog
      link: https://phalcon.io/gab
      name: Gab
    - icon: fontawesome/brands/x-twitter
      link: https://phalcon.io/t
      name: Twitter
    - icon: fontawesome/brands/facebook
      link: https://phalcon.io/fb
      name: Facebook
    - icon: fontawesome/brands/linkedin
      link: https://phalcon.io/linkedin
      name: LinkedIn
    - icon: fontawesome/brands/youtube
      link: https://phalcon.io/youtube
      name: LinkedIn

extra_css:
  - assets/css/extra.css

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - markdown_include.include:
      base_path: docs
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.extra
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.highlight:
      anchor_linenums: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - toc:
      permalink: true

# Page tree
nav:
  - Home:
      - Introduction: introduction.md
      - Changelog:
        - Current Version: https://github.com/phalcon/cphalcon/tree/master/resources
      - Contributing:
        - Contributions: contributions.md
        - Asking a question: https://phalcon.io/discussions
        - Requesting a change: new-feature-request.md
        - Issuing a Pull Request: new-pull-request.md
      - Guides:
        - Backtrace Generation: generating-backtrace.md
        - Reproducible Tests: reproducible-tests.md
      - Sponsoring: sponsors.md
  - Getting Started:
      - Installation: installation.md
      - Webserver Setup: webserver-setup.md
      - WAMP: webserver-wamp.md
      - XAMPP: webserver-xampp.md
      - Environments:
        - Nanobox: environments-nanobox.md
      - Development Tools:
        - Installation: devtools-installation.md
        - Usage: devtools-usage.md
        - Debug: debug.md
      - Tutorials:
          - Basic: tutorial-basic.md
          - Invo: tutorial-invo.md
          - REST: tutorial-rest.md
          - Vokuro: tutorial-vokuro.md
          - Performance: performance.md
  - Core:
      - Application: application.md
      - Micro: application-micro.md
      - CLI: application-cli.md
      - DI Container: di.md
      - MVC: mvc.md
      - Namespaces: namespaces.md
      - API Index: api/index.md
  - Database:
      - Layer: db-layer.md
      - PHQL: db-phql.md
      - ODM: db-odm.md
      - Models: db-models.md
      - Behaviors: db-models-behaviors.md
      - Cache: db-models-cache.md
      - Events: db-models-events.md
      - Metadata: db-models-metadata.md
      - Relationships: db-models-relationships.md
      - Transactions: db-models-transactions.md
      - Validators: db-models-validation.md
      - Pagination: db-pagination.md
      - Migrations: db-migrations.md
  - Front End:
      - Assets: assets.md
      - Flash Messenger: flash.md
      - Forms: forms.md
      - Image: image.md
      - Tag: tag.md
      - View: views.md
      - Volt: volt.md
  - Business Logic:
      - Access Control Lists: acl.md
      - Annotations: annotations.md
      - Controllers: controllers.md
      - Dispatcher: dispatcher.md
      - Event Manager: events.md
      - Filters: filter.md
      - Routing: routing.md
      - Sessions: session.md
      - Url: url.md
      - Validation: validation.md
  - Services:
      - Cache: cache.md
      - Config: config.md
      - Escaper: escaper.md
      - Loader: loader.md
      - Logger: logging.md
      - HTTP:
          - Cookies: cookies.md
          - Request: request.md
          - Response: response.md
      - i18n:
          - Internationalization: i18n.md
          - Translate: translate.md
      - Queue: queue.md
      - Security:
          - Cryptography: crypt.md
          - Security: security.md
